PUT http://localhost:5000/api/empleadores-particular/67e2e28fd8a1b562053331e5
Content-Type: application/json

{
  "nombre": "Juan Pérez",
  "correo": "juan.perez@example.com",
  "telefono": "+34 612345678",
  "fotoPerfil": "https://ejemplo.com/foto.jpg",
  "fechaNacimiento": "1990-05-15T00:00:00.000Z",
  "contraseña": "hashedpassword123",
  "ofertas": ["67e2e1d5d8a1b562053331d2"],
  "valoraciones": []
}