PUT http://localhost:5000/api/candidatos/67e2f84b903202298a9c4678
Content-Type: application/json 

{
    "curriculum": {
      "informacionPersonal": "puta",
      "ubicacion": "Madrid, España",
      "formacionAcademica": "Grado en Ingeniería Informática",
      "experienciaLaboral": "Desarrollador en XYZ Corp por 3 años",
      "idiomas": [
        "Español",
        "Inglés"
      ]
    },
    "correo": "antonio@example.com",
    "telefono": "123456789",
    "fotoPerfil": "https://example.com/foto.jpg",
    "fechaNacimiento": "1990-05-15",
    "contrasena": "secreta123",
    "aplicaciones": [],
    "valoraciones": [],
    "id": "67dc0dc8527fa765ba793399"
  }