POST http://localhost:5000/api/valoraciones-candidato
Content-Type: application/json

{
    "puntuacion": 9,
    "comentario": "Profesional, amable y atento",
    "fecha": "",
    "candidatoId": "6801383d8d60a495da5ed9bd",
    "empleadorId": "6801395d8d60a495da5ed9cf"      
}
