PUT http://localhost:5000/api/ofertas/67fb9bb8e9d0142bddb71c1c
Content-Type: application/json

{
  "titulo": "Cuidador de niños",
  "descripcion": "Buscamos un cuidador de dos niños de 5 y 8 años para los domingos por la tarde.",
  "requisitos": [
    "Experiencia con niños"
  ],
  "duracion": "Indefinida",
  "ubicacion": "Sevilla",
  "salario": 12,
  "imagen": "https://ejemplo.com/imagen.jpg",
  "estado": "Activa",
  "aplicaciones": [],
  "empleadorId": "67fcfb89dd2155fe86155d7e",
  "id": "67fb9bb8e9d0142bddb71c1c"
}